language: python
env:
    - PYTHON=python2.6
    - PYTHON=python2.7
    - PYTHON=python3.2
    - PYTHON=python3.3
    - PYTHON=python3.4
script: make coverage-report
after_success:
    - pip install coveralls && coveralls
